### ISSUE TITLE
有些资源在国内访问不了

### ISSUE THREAD

**Issue by superbible** [Jrohy/k8s-install#1]
1. curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
这个在国外不翻墙不行。
安装这个有什么用？

2. kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
这个在国外也比较困难，偶尔可以访问成功。

**Comment by Jrohy** [comment]
helm安装去掉了
